var sample = require('./sample.js')
var mock = require('mock-fs');
sample.addNumbers('');
sample.simpleAddPos(-3,'');
sample.simpleAddPos(0,'');
sample.simpleAddPos(0,0);
sample.simpleAddPos(0,3);
sample.simpleAddPos(-3,0);
sample.simpleAddPos(3,0);
sample.simpleAddPos(3,undefined);
sample.absolute('',17);
sample.absolute('',-20);
sample.absolute('',20);
sample.absolute('',23);
sample.absolute(-20,20);
sample.absolute(17,20);
sample.absolute(17,17);
sample.absolute(20,17);
sample.absolute(-20,17);
sample.absolute(-20,-20);
sample.absolute(23,-20);
sample.checkRange(-100);
sample.checkRange(103);
sample.checkRange(97);
sample.checkRange(51);
sample.checkRange(100);
sample.divideNumbers('');
sample.compareNumbers('');
